### PR TITLE
Allow bytestring 0.11

### PR DESCRIPTION
**Pull request by sjakobi**
Also fix `cabal test` with added `build-tool-depends`.

### CODE REVIEW

**Comment by sjakobi** [comment]
As a Hackage trustee I have published the relaxed upper bound on `bytestring` as a Hackage revision: https://hackage.haskell.org/package/hjsmin-0.2.0.4/revisions/

**Comment by sjakobi** [comment]
As a Hackage trustee I have published the relaxed upper bound on `bytestring` as a Hackage revision: https://hackage.haskell.org/package/hjsmin-0.2.0.4/revisions/

**Comment by TeofilC** [comment]
It seems like that revision only relaxes the bound on the library component, but the strict bound is kept on the exe component. I think this caused hjsmin to be kicked from the new stackage nightly: https://github.com/commercialhaskell/stackage/blob/758dfa0108595c4a30adccc1fc001c0567587044/build-constraints.yaml#L6508

Could you make another revision @sjakobi ?

**Comment by sjakobi** [comment]
Done: https://hackage.haskell.org/package/hjsmin-0.2.0.4/revisions/

**Comment by erikd** [comment]
Closing.

**Pull request closed without merging**
